# This is a basic workflow that is manually triggered

name: Main workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Compile Java Files
      run: |
        cd Projects/P3
        javac -cp "src/" src/*.java
  

  TestConsume:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
    - uses: actions/checkout@v2
    - name: Run TestConsume
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestConsume
  
  
  TestMapEatCookie:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
    - uses: actions/checkout@v2
    - name: Run TestMapEatCookie
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie
  
  
  TestAttack:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
    - uses: actions/checkout@v2
    - name: Run TestAttack
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestAttack
        
  
  TestMapAttack:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestMapAttack Pacman
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapAttack
  
  TestGhostInRange:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestGhostInRange Pacman
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostInRange
        
  TestPacmanInRange:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestGhostInRange Pacman
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManInRange

  TestPacManMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestPacManMove
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove

  TestGhostMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestGhostMove
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove

  TestMapGetLoc:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestMapGetLoc
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc

  TestPacManValidMoves:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestPacManValidMoves
      run: |
        cd Projects/P3
        javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
        java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves
        
  TestGhostValidMoves:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestGhostValidMoves
      run: |
          cd Projects/P3
          javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves

  TestMapMove:
    runs-on: ubuntu-latest
    container: openjdk

    steps:
    - uses: actions/checkout@v2
    - name: TestMapMove
      run: |
          cd Projects/P3
          javac -cp "tests/junit-4.10.jar:src/:tests" src/*.java tests/*.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove


